# Generated by Django 5.1.4 on 2025-01-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventssp',
            unique_together=set(),
        ),
    ]
