# Generated by Django 5.1.4 on 2025-01-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vendoreventassignment_payment_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendoreventassignment',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20),
        ),
    ]
